use_frameworks!

platform :ios, '9.0'

target 'JSLib_Example' do
  pod 'JSLib', :path => '../'

  target 'JSLib_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase' , '~> 2.1.4'
  end
end
